"""LAMMPS input file generation for DeepMD simulation with constrained metal-water interface."""

LAMMPS_TEMPLATE = """# LAMMPS input for DeepMD simulation with constrained metal-water interface
# Generated by mlip-struct-gen

variable        NSTEPS          equal {nsteps}
variable        THERMO_FREQ     equal {thermo_freq}
variable        DUMP_FREQ       equal {dump_freq}
variable        TEMP            equal {temp}
variable        PRES            equal {pres}
variable        TAU_T           equal {tau_t}
variable        TAU_P           equal {tau_p}

units           metal
boundary        p p p
atom_style      atomic
atom_modify     map array

neighbor        1.0 bin
box             tilt large
read_data       {data_file}
change_box      all triclinic

{masses}

pair_style      deepmd {models} out_freq ${{THERMO_FREQ}} out_file model_devi.out
pair_coeff      * *

{frozen_groups}

thermo_style    custom step temp pe ke etotal press vol lx ly lz xy xz yz
thermo          ${{THERMO_FREQ}}

# Dump with element info
dump            1 all custom ${{DUMP_FREQ}} traj.lammpstrj id type element x y z fx fy fz
dump_modify     1 element {element_list}

{minimization}
velocity        {velocity_group} create ${{TEMP}} {seed}
{ensemble_fix}

timestep        {timestep}
run             ${{NSTEPS}}
"""

# Element masses in g/mol
ELEMENT_MASSES = {
    "H": 1.008,
    "O": 15.9994,
    "Na": 22.98977,
    "K": 39.0983,
    "Li": 6.941,
    "Cs": 132.905,
    "Cl": 35.453,
    "Cu": 63.546,
    "Pt": 195.078,
}


def generate_frozen_groups(constrained_atoms: dict) -> tuple[str, bool]:
    """
    Generate LAMMPS group commands for frozen atoms.

    Args:
        constrained_atoms: Dict with "frozen_atoms" set

    Returns:
        Tuple of (LAMMPS group commands as string, has_frozen_atoms bool)
    """
    frozen_atoms = constrained_atoms.get("frozen_atoms", set())

    if not frozen_atoms:
        return "# No frozen atoms", False

    # Sort atom IDs for consistent output
    sorted_ids = sorted(frozen_atoms)
    id_list = " ".join(str(i) for i in sorted_ids)

    lines = [
        f"# Frozen atoms group ({len(sorted_ids)} atoms)",
        f"group frozen id {id_list}",
        "group mobile subtract all frozen",
        "",
        "# Freeze constrained atoms in place",
        "fix freeze frozen setforce 0.0 0.0 0.0",
    ]

    return "\n".join(lines), True


def generate_mass_lines(elements: list[str]) -> str:
    """
    Generate LAMMPS mass commands for elements.

    Args:
        elements: List of element symbols in type order

    Returns:
        LAMMPS mass commands as string
    """
    lines = []
    for i, elem in enumerate(elements, 1):
        mass = ELEMENT_MASSES.get(elem, 1.0)
        lines.append(f"mass            {i} {mass:.4f}  # {elem}")
    return "\n".join(lines)


def generate_ensemble_fix(ensemble: str, group: str) -> str:
    """
    Generate LAMMPS fix command for the ensemble.

    Args:
        ensemble: "npt" or "nvt"
        group: Group name to apply fix to ("all" or "mobile")

    Returns:
        LAMMPS fix command as string
    """
    if ensemble.lower() == "nvt":
        return f"fix             1 {group} nvt temp ${{TEMP}} ${{TEMP}} ${{TAU_T}}"
    else:  # npt
        return f"fix             1 {group} npt temp ${{TEMP}} ${{TEMP}} ${{TAU_T}} iso ${{PRES}} ${{PRES}} ${{TAU_P}}"


def generate_lammps_input(
    data_file: str,
    model_files: list[str],
    constrained_atoms: dict,
    elements: list[str],
    output_file: str = "in.lammps",
    minimize: bool = False,
    ensemble: str = "npt",
    **kwargs,
) -> str:
    """
    Generate LAMMPS input file for DeepMD simulation with constraints.

    Args:
        data_file: LAMMPS data file name
        model_files: List of DeepMD model files
        constrained_atoms: Dict with constraint info for fix generation
            - "frozen_atoms": set of atom IDs to freeze in place
        elements: List of element symbols for mass and dump_modify
        output_file: Output file path
        minimize: Add energy minimization before MD
        ensemble: "npt" or "nvt"
        **kwargs: MD parameters (nsteps, temp, pres, etc.)

    Returns:
        Path to generated input file
    """
    # Generate mass lines
    masses = generate_mass_lines(elements)

    # Generate model paths
    models = " ".join(model_files)

    # Generate frozen groups (for all constraints)
    frozen_groups, has_frozen = generate_frozen_groups(constrained_atoms)

    # Determine which group to use for velocity and ensemble fix
    velocity_group = "mobile" if has_frozen else "all"
    ensemble_group = "mobile" if has_frozen else "all"

    # Generate ensemble fix command
    ensemble_fix = generate_ensemble_fix(ensemble, ensemble_group)

    # Generate minimization block
    if minimize:
        minimization = """# Energy minimization before MD
min_style       cg
minimize        1.0e-6 1.0e-8 1000 10000

"""
    else:
        minimization = ""

    # Element list for dump_modify
    element_list = " ".join(elements)

    content = LAMMPS_TEMPLATE.format(
        nsteps=kwargs.get("nsteps", 1000),
        thermo_freq=kwargs.get("thermo_freq", 10),
        dump_freq=kwargs.get("dump_freq", 10),
        temp=kwargs.get("temp", 300.0),
        pres=kwargs.get("pres", 1.0),
        tau_t=kwargs.get("tau_t", 0.1),
        tau_p=kwargs.get("tau_p", 0.5),
        timestep=kwargs.get("timestep", 0.0005),
        seed=kwargs.get("seed", 12345),
        data_file=data_file,
        models=models,
        masses=masses,
        frozen_groups=frozen_groups,
        minimization=minimization,
        element_list=element_list,
        velocity_group=velocity_group,
        ensemble_fix=ensemble_fix,
    )

    with open(output_file, "w") as f:
        f.write(content)

    return output_file
