"""LAMMPS input file generation for DeepMD simulation with constrained metal-water interface."""

LAMMPS_TEMPLATE = """# LAMMPS input for DeepMD simulation with constrained metal-water interface
# Generated by mlip-struct-gen

variable        NSTEPS          equal {nsteps}
variable        THERMO_FREQ     equal {thermo_freq}
variable        DUMP_FREQ       equal {dump_freq}
variable        TEMP            equal {temp}
variable        PRES            equal {pres}
variable        TAU_T           equal {tau_t}
variable        TAU_P           equal {tau_p}

units           metal
boundary        p p p
atom_style      atomic

neighbor        1.0 bin
box             tilt large
read_data       {data_file}
change_box      all triclinic

{masses}

pair_style      deepmd {models} out_freq ${{THERMO_FREQ}} out_file model_devi.out
pair_coeff      * *

{constraints}

thermo_style    custom step temp pe ke etotal press vol lx ly lz xy xz yz
thermo          ${{THERMO_FREQ}}

# Dump with element info
dump            1 all custom ${{DUMP_FREQ}} traj.lammpstrj id type element x y z fx fy fz
dump_modify     1 element {element_list}

{minimization}
velocity        all create ${{TEMP}} {seed}
fix             1 all npt temp ${{TEMP}} ${{TEMP}} ${{TAU_T}} iso ${{PRES}} ${{PRES}} ${{TAU_P}}

timestep        {timestep}
run             ${{NSTEPS}}
"""

# Element masses in g/mol
ELEMENT_MASSES = {
    "H": 1.008,
    "O": 15.9994,
    "Na": 22.98977,
    "K": 39.0983,
    "Li": 6.941,
    "Cs": 132.905,
    "Cl": 35.453,
    "Cu": 63.546,
    "Pt": 195.078,
}


def generate_constraint_fixes(
    constrained_atoms: dict,
    constraint_type: str = "rigid",
    harmonic_k: float = 100.0,
) -> str:
    """
    Generate LAMMPS fix commands for constraints.

    Args:
        constrained_atoms: Dict with "distance" and "angle" lists
        constraint_type: "rigid" (K=10000) or "harmonic" (user K)
        harmonic_k: Spring constant for harmonic constraints

    Returns:
        LAMMPS fix commands as string
    """
    if constraint_type == "rigid":
        k_dist = 10000.0
        k_angle = 10000.0
    else:  # harmonic
        k_dist = harmonic_k
        k_angle = harmonic_k

    lines = [f"# Constraints (type: {constraint_type}, K={k_dist})"]

    # Distance constraints (Metal-O, Metal-H, O-H bonds, O-O intermolecular)
    dist_constraints = constrained_atoms.get("distance", [])
    if dist_constraints:
        lines.append("# Distance constraints")
        for i, (id1, id2, dist) in enumerate(dist_constraints):
            lines.append(
                f"fix constrain_dist_{i} all restrain bond {id1} {id2} {k_dist} {k_dist} {dist}"
            )

    # Angle constraints (Metal-O-H, H-O-H)
    angle_constraints = constrained_atoms.get("angle", [])
    if angle_constraints:
        lines.append("")
        lines.append("# Angle constraints")
        for i, (id1, id2, id3, angle) in enumerate(angle_constraints):
            lines.append(
                f"fix constrain_angle_{i} all restrain angle {id1} {id2} {id3} {k_angle} {k_angle} {angle}"
            )

    if not dist_constraints and not angle_constraints:
        return "# No constraints applied"

    return "\n".join(lines)


def generate_mass_lines(elements: list[str]) -> str:
    """
    Generate LAMMPS mass commands for elements.

    Args:
        elements: List of element symbols in type order

    Returns:
        LAMMPS mass commands as string
    """
    lines = []
    for i, elem in enumerate(elements, 1):
        mass = ELEMENT_MASSES.get(elem, 1.0)
        lines.append(f"mass            {i} {mass:.4f}  # {elem}")
    return "\n".join(lines)


def generate_lammps_input(
    data_file: str,
    model_files: list[str],
    constrained_atoms: dict,
    elements: list[str],
    output_file: str = "in.lammps",
    constraint_type: str = "rigid",
    harmonic_k: float = 100.0,
    minimize: bool = False,
    **kwargs,
) -> str:
    """
    Generate LAMMPS input file for DeepMD simulation with constraints.

    Args:
        data_file: LAMMPS data file name
        model_files: List of DeepMD model files
        constrained_atoms: Dict with constraint info for fix generation
        elements: List of element symbols for mass and dump_modify
        output_file: Output file path
        constraint_type: "rigid" or "harmonic"
        harmonic_k: Spring constant for harmonic constraints
        minimize: Add energy minimization before MD
        **kwargs: MD parameters (nsteps, temp, pres, etc.)

    Returns:
        Path to generated input file
    """
    # Generate mass lines
    masses = generate_mass_lines(elements)

    # Generate model paths
    models = " ".join(model_files)

    # Generate constraint fixes
    constraints = generate_constraint_fixes(constrained_atoms, constraint_type, harmonic_k)

    # Generate minimization block
    if minimize:
        minimization = """# Energy minimization before MD
min_style       cg
minimize        1.0e-6 1.0e-8 1000 10000

"""
    else:
        minimization = ""

    # Element list for dump_modify
    element_list = " ".join(elements)

    content = LAMMPS_TEMPLATE.format(
        nsteps=kwargs.get("nsteps", 1000),
        thermo_freq=kwargs.get("thermo_freq", 10),
        dump_freq=kwargs.get("dump_freq", 10),
        temp=kwargs.get("temp", 300.0),
        pres=kwargs.get("pres", 1.0),
        tau_t=kwargs.get("tau_t", 0.1),
        tau_p=kwargs.get("tau_p", 0.5),
        timestep=kwargs.get("timestep", 0.0005),
        seed=kwargs.get("seed", 12345),
        data_file=data_file,
        models=models,
        masses=masses,
        constraints=constraints,
        minimization=minimization,
        element_list=element_list,
    )

    with open(output_file, "w") as f:
        f.write(content)

    return output_file
