"""Input parameters for LAMMPS MD simulation setup."""

from dataclasses import dataclass
from typing import Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from ..utils.logger import MLIPLogger


@dataclass
class LAMMPSInputParameters:
    """
    Parameters for LAMMPS MD simulation input file generation.
    
    This dataclass defines all the parameters needed to generate a LAMMPS
    input file for molecular dynamics simulations. Parameters are validated
    when the LAMMPSInputGenerator is created.
    
    Args:
        lammps_data_file: Path to LAMMPS data file (structure with topology).
            Must be a .data file generated by the water box generator or other structure generator.
            
        output_file: Path to output LAMMPS input script. Will have .in extension
            added automatically if not provided.
            
        water_model: Water model to use for force field parameters.
            Supported models:
            - "SPC/E": Simple Point Charge/Extended model
            - "TIP3P": Transferable Intermolecular Potential 3-Point model  
            - "TIP4P": Transferable Intermolecular Potential 4-Point model
            This determines the LJ parameters and whether SHAKE constraints are used.
            
        ensemble: Statistical ensemble for the simulation.
            - "NVE": Microcanonical ensemble (constant N, V, E)
            - "NVT": Canonical ensemble (constant N, V, T) - uses Nosé-Hoover thermostat
            - "NPT": Isothermal-isobaric ensemble (constant N, P, T) - uses Nosé-Hoover
            
        temperature: Target temperature in Kelvin.
            Valid range: 250-400 K (typical for water simulations)
            
        pressure: Target pressure in atm (only used for NPT ensemble).
            Default: 1.0 atm. Valid range: 0.1-10.0 atm
            
        equilibration_time: Equilibration time in picoseconds.
            Default: 100 ps. The system will equilibrate before production.
            Valid range: 10-1000 ps
            
        production_time: Production time in picoseconds.
            Default: 500 ps. This is the actual data collection phase.
            Valid range: 50-10000 ps
            
        timestep: Integration timestep in femtoseconds.
            Default: 1.0 fs (recommended for water with SHAKE)
            Valid range: 0.5-2.0 fs
            
        pair_style: LAMMPS pair style for intermolecular interactions.
            Default: "lj/cut/coul/long" (LJ with long-range Coulombics via PPPM).
            Common alternatives:
            - "lj/cut/coul/cut": Truncated LJ and Coulombic interactions
            - "lj/cut/coul/debye": LJ with Debye-Hückel screening
            - "lj/charmm/coul/long": CHARMM-style LJ with long-range Coulombics
            
        pair_style_cutoff: Cutoff distance for pair interactions in Angstroms.
            Default: 6.0 Å. This sets the cutoff for both LJ and Coulombic interactions.
            Typical range: 6.0-12.0 Å for water simulations.
            
        use_shake: Whether to use SHAKE constraints for rigid water models.
            Default: True for rigid water models (SPC/E, TIP3P, TIP4P)
            SHAKE constrains bond lengths and angles in water molecules.
            
        shake_tolerance: Tolerance for SHAKE convergence.
            Default: 1e-6. Only used if use_shake=True.
            
        thermostat_damping: Damping parameter for Nosé-Hoover thermostat (ps).
            Default: 0.1 ps. Only used for NVT and NPT ensembles.
            Valid range: 0.05-1.0 ps
            
        barostat_damping: Damping parameter for Nosé-Hoover barostat (ps).
            Default: 1.0 ps. Only used for NPT ensemble.
            Valid range: 0.5-5.0 ps
            
        output_frequency: Frequency for trajectory output (steps).
            Default: 1000 steps. Controls how often coordinates are written.
            
        dump_freq: Frequency for production dump output in picoseconds.
            Default: 1.0 ps. Controls spacing of trajectory dumps during production.
            Will be converted to steps based on timestep.
            
        thermo_frequency: Frequency for thermodynamic output (steps).
            Default: 100 steps. Controls how often energies/temp/press are printed.
            
        seed: Random seed for velocity initialization and thermostats.
            Default: 12345. Must be positive integer.
            
        log: Enable logging output during input file generation.
            If True and logger is None, creates a new MLIPLogger instance.
            
        logger: Custom MLIPLogger instance for logging. If None and log=True,
            a new logger will be created automatically.
    
    Examples:
        Basic NVT simulation at 300K:
        >>> params = LAMMPSInputParameters(
        ...     lammps_data_file="water_box.data",
        ...     output_file="nvt_simulation",
        ...     water_model="SPC/E",
        ...     ensemble="NVT",
        ...     temperature=300.0
        ... )
        
        NPT simulation with custom parameters:
        >>> params = LAMMPSInputParameters(
        ...     lammps_data_file="water_box.data", 
        ...     output_file="npt_simulation",
        ...     water_model="TIP3P",
        ...     ensemble="NPT",
        ...     temperature=298.15,
        ...     pressure=1.0,
        ...     equilibration_time=200.0,
        ...     production_time=1000.0,
        ...     log=True
        ... )
        
        NVE simulation without SHAKE:
        >>> params = LAMMPSInputParameters(
        ...     lammps_data_file="water_box.data",
        ...     output_file="nve_simulation", 
        ...     water_model="SPC/E",
        ...     ensemble="NVE",
        ...     temperature=300.0,  # Only for initial velocities
        ...     use_shake=False,
        ...     timestep=0.5  # Smaller timestep without constraints
        ... )
    
    Note:
        All validation is performed when creating a LAMMPSInputGenerator instance,
        not when creating this parameters object. The water_model parameter
        determines the appropriate LJ parameters and SHAKE settings.
    """
    
    lammps_data_file: str
    output_file: str
    water_model: str
    ensemble: str
    temperature: float
    pressure: float = 1.0
    equilibration_time: float = 100.0
    production_time: float = 500.0
    timestep: float = 1.0
    pair_style: str = "lj/cut/coul/long"
    pair_style_cutoff: float = 6.0
    use_shake: Optional[bool] = None  # Auto-determined from water model if None
    shake_tolerance: float = 1e-6
    thermostat_damping: float = 0.1
    barostat_damping: float = 1.0
    output_frequency: int = 1000
    dump_freq: float = 1.0
    thermo_frequency: int = 100
    seed: int = 12345
    log: bool = False
    logger: Optional["MLIPLogger"] = None