# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Essential file hygiene hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Ruff: Fast Python linter and formatter (replaces black, isort, flake8, and more)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
        exclude: ^(examples/|experiments/)
      - id: ruff-format
        exclude: ^(examples/|experiments/)

# Configuration for pre-commit CI
ci:
  autoupdate_schedule: monthly
