"""LAMMPS input file generation for DeepMD simulation with spring restraints."""

LAMMPS_TEMPLATE = """# LAMMPS input for DeepMD simulation with spring-restrained water
# Generated by mlip-struct-gen

variable        NSTEPS          equal {nsteps}
variable        THERMO_FREQ     equal {thermo_freq}
variable        DUMP_FREQ       equal {dump_freq}
variable        TEMP            equal {temp}
variable        PRES            equal {pres}
variable        TAU_T           equal {tau_t}
variable        TAU_P           equal {tau_p}

units           metal
boundary        p p p
atom_style      atomic
atom_modify     map array

neighbor        1.0 bin
box             tilt large
read_data       {data_file}
change_box      all triclinic

{masses}

pair_style      deepmd {models} out_freq ${{THERMO_FREQ}} out_file model_devi.out
pair_coeff      * *

{spring_restraints}

thermo_style    custom step temp pe ke etotal press vol lx ly lz xy xz yz
thermo          ${{THERMO_FREQ}}

# Dump with element info
dump            1 all custom ${{DUMP_FREQ}} traj.lammpstrj id type element x y z fx fy fz
dump_modify     1 element {element_list}

{minimization}
velocity        all create ${{TEMP}} {seed}
{ensemble_fix}

timestep        {timestep}
run             ${{NSTEPS}}
"""

# Element masses in g/mol
ELEMENT_MASSES = {
    "H": 1.008,
    "O": 15.9994,
    "Na": 22.98977,
    "Cl": 35.453,
    "K": 39.0983,
    "Li": 6.941,
    "Ca": 40.078,
    "Mg": 24.305,
    "Br": 79.904,
    "Cs": 132.905,
    "Pt": 195.078,
    "Au": 196.967,
    "Ag": 107.868,
    "Cu": 63.546,
    "Ni": 58.693,
    "Pd": 106.42,
    "Fe": 55.845,
}


def generate_spring_restraints(spring_bonds: list[dict]) -> str:
    """
    Generate LAMMPS fix restrain commands for spring bonds.

    Args:
        spring_bonds: List of dicts with atom1_id, atom2_id, k_spring, distance

    Returns:
        LAMMPS fix restrain commands as string
    """
    if not spring_bonds:
        return "# No spring restraints"

    lines = [
        f"# Spring bond restraints ({len(spring_bonds)} bonds)",
    ]

    for i, bond in enumerate(spring_bonds):
        atom1 = bond["atom1_id"]
        atom2 = bond["atom2_id"]
        k = bond["k_spring"]
        r0 = bond["distance"]
        # fix ID group-ID restrain bond atom1 atom2 Kstart Kstop r0
        lines.append(f"fix spring{i+1} all restrain bond {atom1} {atom2} {k} {k} {r0}")

    return "\n".join(lines)


def generate_mass_lines(elements: list[str]) -> str:
    """
    Generate LAMMPS mass commands for elements.

    Args:
        elements: List of element symbols in type order

    Returns:
        LAMMPS mass commands as string
    """
    lines = []
    for i, elem in enumerate(elements, 1):
        mass = ELEMENT_MASSES.get(elem, 1.0)
        lines.append(f"mass            {i} {mass:.4f}  # {elem}")
    return "\n".join(lines)


def generate_ensemble_fix(ensemble: str, group: str = "all") -> str:
    """
    Generate LAMMPS fix command for the ensemble.

    Args:
        ensemble: "npt" or "nvt"
        group: Group name to apply fix to

    Returns:
        LAMMPS fix command as string
    """
    if ensemble.lower() == "nvt":
        return f"fix             1 {group} nvt temp ${{TEMP}} ${{TEMP}} ${{TAU_T}}"
    else:  # npt
        return f"fix             1 {group} npt temp ${{TEMP}} ${{TEMP}} ${{TAU_T}} iso ${{PRES}} ${{PRES}} ${{TAU_P}}"


def generate_lammps_input(
    data_file: str,
    model_files: list[str],
    spring_bonds: list[dict],
    output_file: str = "in.lammps",
    minimize: bool = False,
    ensemble: str = "npt",
    elements: list[str] | None = None,
    **kwargs,
) -> str:
    """
    Generate LAMMPS input file for DeepMD simulation with spring restraints.

    Args:
        data_file: LAMMPS data file name
        model_files: List of DeepMD model files
        spring_bonds: List of spring bond dicts with atom1_id, atom2_id, k_spring, distance
        output_file: Output file path
        minimize: Add energy minimization before MD
        ensemble: "npt" or "nvt"
        elements: List of element symbols for type mapping (default: ["O", "H"])
        **kwargs: MD parameters (nsteps, temp, pres, etc.)

    Returns:
        Path to generated input file
    """
    if elements is None:
        elements = ["O", "H"]

    # Generate mass lines
    masses = generate_mass_lines(elements)

    # Generate model paths
    models = " ".join(model_files)

    # Generate spring restraints
    spring_restraints = generate_spring_restraints(spring_bonds)

    # Generate ensemble fix command
    ensemble_fix = generate_ensemble_fix(ensemble, "all")

    # Generate minimization block
    if minimize:
        minimization = """# Energy minimization before MD
min_style       cg
minimize        1.0e-6 1.0e-8 1000 10000

"""
    else:
        minimization = ""

    # Element list for dump_modify
    element_list = " ".join(elements)

    content = LAMMPS_TEMPLATE.format(
        nsteps=kwargs.get("nsteps", 10000),
        thermo_freq=kwargs.get("thermo_freq", 10),
        dump_freq=kwargs.get("dump_freq", 10),
        temp=kwargs.get("temp", 300.0),
        pres=kwargs.get("pres", 1.0),
        tau_t=kwargs.get("tau_t", 0.1),
        tau_p=kwargs.get("tau_p", 0.5),
        timestep=kwargs.get("timestep", 0.0005),
        seed=kwargs.get("seed", 12345),
        data_file=data_file,
        models=models,
        masses=masses,
        spring_restraints=spring_restraints,
        minimization=minimization,
        element_list=element_list,
        ensemble_fix=ensemble_fix,
    )

    with open(output_file, "w") as f:
        f.write(content)

    return output_file
